AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - test/files/**/*
    - lib/kramdown/parser/pot_markdown/table.rb

AsciiComments:
  Enabled: false

ClassLength:
  Max: 200

Documentation:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Max: 30

PerceivedComplexity:
  Exclude:
    - lib/kramdown/**/*

inherit_from: .rubocop_todo.yml
